### ISSUE TITLE
Network header

### ISSUE THREAD

**Issue by dimske-sys** [dimske-sys/datespot#28]
The file named "src/Engine/Network.h" contains certain mistakes in its syntax that need to be corrected. Additionally, there are templates in the file that have not been clearly defined and need to be resolved. In order for the file to function properly, these issues must be addressed and fixed.

**Comment by jai-bhardwaj** [comment]
Hi, @dimske-sys can you provide a description of the issue?

**Comment by dimske-sys** [comment]
@jai-bhardwaj Hi there! Their are some syntax errors in the "src/Engine/Network.h" file and undefined templates as well. This could potentially cause issues with the compilation process and may prevent the program from running correctly in the feature. I would suggest opening the file in Visual Studio setting up your C++ 20 compiler to see the errors and warnings in more detail. Once you identify the issues, you can start working on fixing them.
